//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Postamat
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Постамат.
    /// </summary>
    // *** Start programmer edit section *** (Постамат CustomAttributes)

    // *** End programmer edit section *** (Постамат CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ПостаматE", new string[] {
            "НомерПостамата as \'Номер постамата\'",
            "СтатусПостамата as \'Статус постамата\'",
            "Адрес as \'Адрес\'",
            "Адрес.Адрес as \'Адрес\'"}, Hidden=new string[] {
            "Адрес.Адрес"})]
    [AssociatedDetailViewAttribute("ПостаматE", "Ячейка", "ЯчейкаE", true, "", "Ячейка", true, new string[] {
            ""})]
    [MasterViewDefineAttribute("ПостаматE", "Адрес", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Адрес")]
    [View("ПостаматL", new string[] {
            "НомерПостамата as \'Номер постамата\'",
            "СтатусПостамата as \'Статус постамата\'",
            "Адрес.Адрес as \'Адрес\'"})]
    public class Постамат : ICSSoft.STORMNET.DataObject
    {
        
        private int fНомерПостамата;
        
        private IIS.Postamat.СтатПост fСтатусПостамата;
        
        private IIS.Postamat.Адрес fАдрес;
        
        private IIS.Postamat.DetailArrayOfЯчейка fЯчейка;
        
        // *** Start programmer edit section *** (Постамат CustomMembers)

        // *** End programmer edit section *** (Постамат CustomMembers)

        
        /// <summary>
        /// НомерПостамата.
        /// </summary>
        // *** Start programmer edit section *** (Постамат.НомерПостамата CustomAttributes)

        // *** End programmer edit section *** (Постамат.НомерПостамата CustomAttributes)
        public virtual int НомерПостамата
        {
            get
            {
                // *** Start programmer edit section *** (Постамат.НомерПостамата Get start)

                // *** End programmer edit section *** (Постамат.НомерПостамата Get start)
                int result = this.fНомерПостамата;
                // *** Start programmer edit section *** (Постамат.НомерПостамата Get end)

                // *** End programmer edit section *** (Постамат.НомерПостамата Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Постамат.НомерПостамата Set start)

                // *** End programmer edit section *** (Постамат.НомерПостамата Set start)
                this.fНомерПостамата = value;
                // *** Start programmer edit section *** (Постамат.НомерПостамата Set end)

                // *** End programmer edit section *** (Постамат.НомерПостамата Set end)
            }
        }
        
        /// <summary>
        /// СтатусПостамата.
        /// </summary>
        // *** Start programmer edit section *** (Постамат.СтатусПостамата CustomAttributes)

        // *** End programmer edit section *** (Постамат.СтатусПостамата CustomAttributes)
        public virtual IIS.Postamat.СтатПост СтатусПостамата
        {
            get
            {
                // *** Start programmer edit section *** (Постамат.СтатусПостамата Get start)

                // *** End programmer edit section *** (Постамат.СтатусПостамата Get start)
                IIS.Postamat.СтатПост result = this.fСтатусПостамата;
                // *** Start programmer edit section *** (Постамат.СтатусПостамата Get end)

                // *** End programmer edit section *** (Постамат.СтатусПостамата Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Постамат.СтатусПостамата Set start)

                // *** End programmer edit section *** (Постамат.СтатусПостамата Set start)
                this.fСтатусПостамата = value;
                // *** Start programmer edit section *** (Постамат.СтатусПостамата Set end)

                // *** End programmer edit section *** (Постамат.СтатусПостамата Set end)
            }
        }
        
        /// <summary>
        /// Постамат.
        /// </summary>
        // *** Start programmer edit section *** (Постамат.Адрес CustomAttributes)

        // *** End programmer edit section *** (Постамат.Адрес CustomAttributes)
        [PropertyStorage(new string[] {
                "Адрес"})]
        [NotNull()]
        public virtual IIS.Postamat.Адрес Адрес
        {
            get
            {
                // *** Start programmer edit section *** (Постамат.Адрес Get start)

                // *** End programmer edit section *** (Постамат.Адрес Get start)
                IIS.Postamat.Адрес result = this.fАдрес;
                // *** Start programmer edit section *** (Постамат.Адрес Get end)

                // *** End programmer edit section *** (Постамат.Адрес Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Постамат.Адрес Set start)

                // *** End programmer edit section *** (Постамат.Адрес Set start)
                this.fАдрес = value;
                // *** Start programmer edit section *** (Постамат.Адрес Set end)

                // *** End programmer edit section *** (Постамат.Адрес Set end)
            }
        }
        
        /// <summary>
        /// Постамат.
        /// </summary>
        // *** Start programmer edit section *** (Постамат.Ячейка CustomAttributes)

        // *** End programmer edit section *** (Постамат.Ячейка CustomAttributes)
        public virtual IIS.Postamat.DetailArrayOfЯчейка Ячейка
        {
            get
            {
                // *** Start programmer edit section *** (Постамат.Ячейка Get start)

                // *** End programmer edit section *** (Постамат.Ячейка Get start)
                if ((this.fЯчейка == null))
                {
                    this.fЯчейка = new IIS.Postamat.DetailArrayOfЯчейка(this);
                }
                IIS.Postamat.DetailArrayOfЯчейка result = this.fЯчейка;
                // *** Start programmer edit section *** (Постамат.Ячейка Get end)

                // *** End programmer edit section *** (Постамат.Ячейка Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Постамат.Ячейка Set start)

                // *** End programmer edit section *** (Постамат.Ячейка Set start)
                this.fЯчейка = value;
                // *** Start programmer edit section *** (Постамат.Ячейка Set end)

                // *** End programmer edit section *** (Постамат.Ячейка Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ПостаматE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ПостаматE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ПостаматE", typeof(IIS.Postamat.Постамат));
                }
            }
            
            /// <summary>
            /// "ПостаматL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ПостаматL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ПостаматL", typeof(IIS.Postamat.Постамат));
                }
            }
        }
    }
}
