//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Postamat
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Посылка.
    /// </summary>
    // *** Start programmer edit section *** (Посылка CustomAttributes)

    // *** End programmer edit section *** (Посылка CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ПосылкаE", new string[] {
            "НомерПостамата as \'Номер постамата\'",
            "НомерПосылки as \'Номер посылки\'",
            "НомерЯчейки as \'Номер ячейки\'",
            "Транзакция as \'Транзакция\'",
            "Логистика as \'Логистика\'",
            "Логистика.Номер as \'Номер\'",
            "Транзакция.Дата as \'Дата\'",
            "Транзакция.Время as \'Время\'",
            "Транзакция.Оплата as \'Оплата\'",
            "Транзакция.Сумма as \'Сумма\'",
            "СгенКод.СгенКод as \'Сгенерировать код\'",
            "СгенКод as \'Сгенерировать код\'"}, Hidden=new string[] {
            "Логистика.Номер",
            "Транзакция.Время",
            "СгенКод.СгенКод"})]
    [MasterViewDefineAttribute("ПосылкаE", "Транзакция", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Время")]
    [MasterViewDefineAttribute("ПосылкаE", "Логистика", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Номер")]
    [MasterViewDefineAttribute("ПосылкаE", "СгенКод", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "СгенКод")]
    public class Посылка : ICSSoft.STORMNET.DataObject
    {
        
        private int fНомерПостамата;
        
        private int fНомерПосылки;
        
        private int fНомерЯчейки;
        
        private IIS.Postamat.Транзакция fТранзакция;
        
        private IIS.Postamat.Логистика fЛогистика;
        
        private IIS.Postamat.СгенКод fСгенКод;
        
        private IIS.Postamat.Хранение fХранение;
        
        // *** Start programmer edit section *** (Посылка CustomMembers)

        // *** End programmer edit section *** (Посылка CustomMembers)

        
        /// <summary>
        /// НомерПостамата.
        /// </summary>
        // *** Start programmer edit section *** (Посылка.НомерПостамата CustomAttributes)

        // *** End programmer edit section *** (Посылка.НомерПостамата CustomAttributes)
        public virtual int НомерПостамата
        {
            get
            {
                // *** Start programmer edit section *** (Посылка.НомерПостамата Get start)

                // *** End programmer edit section *** (Посылка.НомерПостамата Get start)
                int result = this.fНомерПостамата;
                // *** Start programmer edit section *** (Посылка.НомерПостамата Get end)

                // *** End programmer edit section *** (Посылка.НомерПостамата Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Посылка.НомерПостамата Set start)

                // *** End programmer edit section *** (Посылка.НомерПостамата Set start)
                this.fНомерПостамата = value;
                // *** Start programmer edit section *** (Посылка.НомерПостамата Set end)

                // *** End programmer edit section *** (Посылка.НомерПостамата Set end)
            }
        }
        
        /// <summary>
        /// НомерПосылки.
        /// </summary>
        // *** Start programmer edit section *** (Посылка.НомерПосылки CustomAttributes)

        // *** End programmer edit section *** (Посылка.НомерПосылки CustomAttributes)
        public virtual int НомерПосылки
        {
            get
            {
                // *** Start programmer edit section *** (Посылка.НомерПосылки Get start)

                // *** End programmer edit section *** (Посылка.НомерПосылки Get start)
                int result = this.fНомерПосылки;
                // *** Start programmer edit section *** (Посылка.НомерПосылки Get end)

                // *** End programmer edit section *** (Посылка.НомерПосылки Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Посылка.НомерПосылки Set start)

                // *** End programmer edit section *** (Посылка.НомерПосылки Set start)
                this.fНомерПосылки = value;
                // *** Start programmer edit section *** (Посылка.НомерПосылки Set end)

                // *** End programmer edit section *** (Посылка.НомерПосылки Set end)
            }
        }
        
        /// <summary>
        /// НомерЯчейки.
        /// </summary>
        // *** Start programmer edit section *** (Посылка.НомерЯчейки CustomAttributes)

        // *** End programmer edit section *** (Посылка.НомерЯчейки CustomAttributes)
        public virtual int НомерЯчейки
        {
            get
            {
                // *** Start programmer edit section *** (Посылка.НомерЯчейки Get start)

                // *** End programmer edit section *** (Посылка.НомерЯчейки Get start)
                int result = this.fНомерЯчейки;
                // *** Start programmer edit section *** (Посылка.НомерЯчейки Get end)

                // *** End programmer edit section *** (Посылка.НомерЯчейки Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Посылка.НомерЯчейки Set start)

                // *** End programmer edit section *** (Посылка.НомерЯчейки Set start)
                this.fНомерЯчейки = value;
                // *** Start programmer edit section *** (Посылка.НомерЯчейки Set end)

                // *** End programmer edit section *** (Посылка.НомерЯчейки Set end)
            }
        }
        
        /// <summary>
        /// Посылка.
        /// </summary>
        // *** Start programmer edit section *** (Посылка.Логистика CustomAttributes)

        // *** End programmer edit section *** (Посылка.Логистика CustomAttributes)
        [PropertyStorage(new string[] {
                "Логистика"})]
        [NotNull()]
        public virtual IIS.Postamat.Логистика Логистика
        {
            get
            {
                // *** Start programmer edit section *** (Посылка.Логистика Get start)

                // *** End programmer edit section *** (Посылка.Логистика Get start)
                IIS.Postamat.Логистика result = this.fЛогистика;
                // *** Start programmer edit section *** (Посылка.Логистика Get end)

                // *** End programmer edit section *** (Посылка.Логистика Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Посылка.Логистика Set start)

                // *** End programmer edit section *** (Посылка.Логистика Set start)
                this.fЛогистика = value;
                // *** Start programmer edit section *** (Посылка.Логистика Set end)

                // *** End programmer edit section *** (Посылка.Логистика Set end)
            }
        }
        
        /// <summary>
        /// Посылка.
        /// </summary>
        // *** Start programmer edit section *** (Посылка.СгенКод CustomAttributes)

        // *** End programmer edit section *** (Посылка.СгенКод CustomAttributes)
        [PropertyStorage(new string[] {
                "СгенКод"})]
        [NotNull()]
        public virtual IIS.Postamat.СгенКод СгенКод
        {
            get
            {
                // *** Start programmer edit section *** (Посылка.СгенКод Get start)

                // *** End programmer edit section *** (Посылка.СгенКод Get start)
                IIS.Postamat.СгенКод result = this.fСгенКод;
                // *** Start programmer edit section *** (Посылка.СгенКод Get end)

                // *** End programmer edit section *** (Посылка.СгенКод Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Посылка.СгенКод Set start)

                // *** End programmer edit section *** (Посылка.СгенКод Set start)
                this.fСгенКод = value;
                // *** Start programmer edit section *** (Посылка.СгенКод Set end)

                // *** End programmer edit section *** (Посылка.СгенКод Set end)
            }
        }
        
        /// <summary>
        /// Посылка.
        /// </summary>
        // *** Start programmer edit section *** (Посылка.Транзакция CustomAttributes)

        // *** End programmer edit section *** (Посылка.Транзакция CustomAttributes)
        [PropertyStorage(new string[] {
                "Транзакция"})]
        [NotNull()]
        public virtual IIS.Postamat.Транзакция Транзакция
        {
            get
            {
                // *** Start programmer edit section *** (Посылка.Транзакция Get start)

                // *** End programmer edit section *** (Посылка.Транзакция Get start)
                IIS.Postamat.Транзакция result = this.fТранзакция;
                // *** Start programmer edit section *** (Посылка.Транзакция Get end)

                // *** End programmer edit section *** (Посылка.Транзакция Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Посылка.Транзакция Set start)

                // *** End programmer edit section *** (Посылка.Транзакция Set start)
                this.fТранзакция = value;
                // *** Start programmer edit section *** (Посылка.Транзакция Set end)

                // *** End programmer edit section *** (Посылка.Транзакция Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку IIS.Postamat.Хранение.
        /// </summary>
        // *** Start programmer edit section *** (Посылка.Хранение CustomAttributes)

        // *** End programmer edit section *** (Посылка.Хранение CustomAttributes)
        [Agregator()]
        [NotNull()]
        [PropertyStorage(new string[] {
                "Хранение"})]
        public virtual IIS.Postamat.Хранение Хранение
        {
            get
            {
                // *** Start programmer edit section *** (Посылка.Хранение Get start)

                // *** End programmer edit section *** (Посылка.Хранение Get start)
                IIS.Postamat.Хранение result = this.fХранение;
                // *** Start programmer edit section *** (Посылка.Хранение Get end)

                // *** End programmer edit section *** (Посылка.Хранение Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Посылка.Хранение Set start)

                // *** End programmer edit section *** (Посылка.Хранение Set start)
                this.fХранение = value;
                // *** Start programmer edit section *** (Посылка.Хранение Set end)

                // *** End programmer edit section *** (Посылка.Хранение Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ПосылкаE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ПосылкаE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ПосылкаE", typeof(IIS.Postamat.Посылка));
                }
            }
        }
    }
    
    /// <summary>
    /// Detail array of Посылка.
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOfПосылка CustomAttributes)

    // *** End programmer edit section *** (DetailArrayDetailArrayOfПосылка CustomAttributes)
    public class DetailArrayOfПосылка : ICSSoft.STORMNET.DetailArray
    {
        
        // *** Start programmer edit section *** (IIS.Postamat.DetailArrayOfПосылка members)

        // *** End programmer edit section *** (IIS.Postamat.DetailArrayOfПосылка members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type Посылка by index.
        /// </summary>
        /// <summary>
        /// Adds object with type Посылка.
        /// </summary>
        public DetailArrayOfПосылка(IIS.Postamat.Хранение fХранение) : 
                base(typeof(Посылка), ((ICSSoft.STORMNET.DataObject)(fХранение)))
        {
        }
        
        public IIS.Postamat.Посылка this[int index]
        {
            get
            {
                return ((IIS.Postamat.Посылка)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(IIS.Postamat.Посылка dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
