//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Postamat
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Стат ячейки.
    /// </summary>
    // *** Start programmer edit section *** (СтатЯчейки CustomAttributes)

    // *** End programmer edit section *** (СтатЯчейки CustomAttributes)
    public enum СтатЯчейки
    {
        
        // *** Start programmer edit section *** (СтатЯчейки.1 CustomAttributes)

        // *** End programmer edit section *** (СтатЯчейки.1 CustomAttributes)
        [Caption("Занято")]
        1,
        
        // *** Start programmer edit section *** (СтатЯчейки.2 CustomAttributes)

        // *** End programmer edit section *** (СтатЯчейки.2 CustomAttributes)
        [Caption("Свободно")]
        2,
    }
}
